[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
 
[functions]
  directory = "netlify/functions"

[[scheduled.functions]]
  name = "keep-supabase-alive"
  schedule = "0 0 * * 0"
